<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Connexion',
        'headline' => 'Connexion',
        'subheadline' => 'Connectez-vous à votre compte ci-dessous',
        'show_subheadline' => false,
        'email_address' => 'Adresse email',
        'password' => 'Mot de passe',
        'remember_me' => 'Se souvenir de moi',
        'edit' => 'Modification',
        'button' => 'Connexion',
        'forget_password' => 'Mot de passe oublié ?',
        'dont_have_an_account' => 'Pas de compte ?',
        'sign_up' => "S'inscrire",
        'social_auth_authenticated_message' => 'You have been authenticated via __social_providers_list__. Please login to that network below.',
        'change_email' => 'Change Email',
        'couldnt_find_your_account' => 'Identifiants invalides',
    ],
    'register' => [
        'page_title' => 'Création de compte',
        'headline' => 'Création de compte',
        'subheadline' => 'Register for your free account below.',
        'show_subheadline' => false,
        'name' => 'Nom',
        'email_address' => 'Adresse email',
        'password' => 'Mot de passe',
        'password_confirmation' => 'Confirmer le mot de passe',
        'already_have_an_account' => 'Vous avez déjà un compte ?',
        'sign_in' => 'Connexion',
        'button' => 'Continuer',
        'email_registration_disabled' => 'Email registration is currently disabled. Please use social login.',
    ],
    'verify' => [
        'page_title' => 'Création de compte',
        'headline' => 'Vérifiez votre adresse email',
        'subheadline' => 'Before you can proceed you must verify your email.',
        'show_subheadline' => false,
        'description' => "Avant de continuer, veuillez consulter votre e-mail pour un lien de vérification. Si vous n'avez pas reçu l'e-mail,",
        'new_request_link' => 'cliquez ici pour en demander un autre',
        'new_link_sent' => 'Un nouveau lien a été envoyé à votre adresse e-mail.',
        'or' => 'Ou',
        'logout' => 'Cliquez ici pour déconnecter',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirmez votre mot de passe',
        'headline' => 'Confirmez votre mot de passe',
        'subheadline' => 'Assurez-vous de confirmer votre mot de passe ci-dessous',
        'show_subheadline' => false,
        'password' => 'Mot de passe',
        'button' => 'Confirmer le mot de passe',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Demander une réinitialisation de mot de passe',
        'headline' => 'Réinitialisation de mot de passe',
        'subheadline' => 'Enter your email below to reset your password',
        'show_subheadline' => false,
        'email' => 'Adresse email',
        'button' => 'Envoyer le lien de réinitialisation du mot de passe',
        'or' => 'ou',
        'return_to_login' => 'retour à la connexion',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Your Password',
        'headline' => 'Reset Password',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'password' => 'Password',
        'password_confirm' => 'Confirm Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Défi à deux facteurs',
        'headline_auth' => "Code d'authentification",
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
